import 'dart:typed_data';
import 'package:ashfoam_sadiq/src/data/models/stock_report.model.dart';
import 'package:ashfoam_sadiq/src/data/models/company.model.dart';
import 'package:ashfoam_sadiq/src/features/common/services/pdf_helper.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class StockReportPrintService {
  static final _currencyFormat = NumberFormat.currency(symbol: 'GH¢');
  static final _dateFormat = DateFormat('MMMM yyyy');
  static final _fullDateFormat = DateFormat('dd MMM yyyy HH:mm');

  static Future<void> printReport(
    StockReportSummary report, {
    CompanyModel? company,
  }) async {
    final pdf = await _generateReport(report, company: company);
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf,
      name: 'Stock_Report_${_dateFormat.format(report.createdAt)}.pdf',
    );
  }

  static Future<void> showPreview(
    BuildContext context,
    StockReportSummary report, {
    CompanyModel? company,
  }) async {
    await showDialog(
      context: context,
      builder: (context) => Dialog(
        child: Container(
          width: 1000,
          height: 800,
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Print Preview - ${_dateFormat.format(report.createdAt)}',
                    style: const TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.pop(context),
                  ),
                ],
              ),
              const Divider(),
              Expanded(
                child: PdfPreview(
                  build: (format) => _generateReport(report, company: company),
                  allowSharing: true,
                  allowPrinting: true,
                  canChangePageFormat: false,
                  initialPageFormat: PdfPageFormat.a4,
                  pdfFileName:
                      'Stock_Report_${_dateFormat.format(report.createdAt)}.pdf',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  static Future<Uint8List> _generateReport(
    StockReportSummary report, {
    CompanyModel? company,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header Section
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  PdfHelper.buildCompanyHeader(company),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        report.branchName,
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),
                      pw.Text(_dateFormat.format(report.createdAt)),
                    ],
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Meta Info
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated By: ${report.createdBy}',
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                    pw.Text(
                      'Printed On: ${_fullDateFormat.format(DateTime.now())}',
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      'Report ID: ${report.id.substring(0, 8)}...',
                      style: const pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey,
                      ),
                    ),
                  ],
                ),
              ],
            ),

            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 20),
              child: pw.Divider(thickness: 0.5),
            ),

            // Product Detail Title
            pw.Text(
              'PRODUCT PERFORMANCE SNAPSHOT',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
            ),
            pw.SizedBox(height: 10),

            // Product Table
            pw.Table(
              border: pw.TableBorder.all(width: 0.5, color: PdfColors.grey400),
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(1),
                3: const pw.FlexColumnWidth(1),
                4: const pw.FlexColumnWidth(2),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _tableHeader('Product'),
                    _tableHeader('SKU'),
                    _tableHeader('Qty', align: pw.TextAlign.center),
                    _tableHeader('Sold', align: pw.TextAlign.center),
                    _tableHeader('Sales', align: pw.TextAlign.right),
                  ],
                ),
                ...report.currentStock.map(
                  (prod) => pw.TableRow(
                    children: [
                      _tableCell(prod.name),
                      _tableCell(prod.sku),
                      _tableCell(
                        prod.quantity.toString(),
                        align: pw.TextAlign.center,
                      ),
                      _tableCell(
                        prod.quantitySold.toString(),
                        align: pw.TextAlign.center,
                      ),
                      _tableCell(
                        _currencyFormat
                            .format(prod.totalSales)
                            .replaceAll('GH¢', ''),
                        align: pw.TextAlign.right,
                      ),
                    ],
                  ),
                ),
              ],
            ),

            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 40),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Divider(thickness: 1, color: PdfColors.grey300),
                  pw.SizedBox(height: 5),
                  pw.Text(
                    'Authorized Signature: ___________________________',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                ],
              ),
            ),
          ];
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,

            child: pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
            ),
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _tableHeader(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
      ),
    );
  }

  static pw.Widget _tableCell(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        textAlign: align,
        style: const pw.TextStyle(fontSize: 9),
      ),
    );
  }
}
