import 'dart:typed_data';
import 'package:ashfoam_sadiq/src/data/local/app_database.dart' hide WayBill;
import 'package:ashfoam_sadiq/src/data/models/profoma.model.dart';
import 'package:ashfoam_sadiq/src/data/models/waybill.model.dart';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class WaybillPrintService {
  static final _dateFormat = DateFormat('dd MMM yyyy');
  static final _currencyFormat = NumberFormat.currency(symbol: 'GH¢');

  static Future<void> showPreview({
    required BuildContext context,
    required WayBill waybill,
    required List<ProductDetails> items,
    required Branche? branch,
  }) async {
    await showDialog(
      context: context,
      builder: (context) => Dialog(
        child: Container(
          width: 1000,
          height: 800,
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Waybill Preview - ${waybill.orderNumber}',
                    style: const TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.pop(context),
                  ),
                ],
              ),
              const Divider(),
              Expanded(
                child: PdfPreview(
                  build: (format) => _generatePdf(waybill, items, branch),
                  allowSharing: true,
                  allowPrinting: true,
                  canChangePageFormat: false,
                  initialPageFormat: PdfPageFormat.a4,
                  pdfFileName: 'Waybill_${waybill.dispatchDocNumber}.pdf',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  static Future<Uint8List> _generatePdf(
    WayBill waybill,
    List<ProductDetails> items,
    Branche? branch,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Company Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'KUMASI ASHFOAM',
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 24,
                      ),
                    ),
                    if (branch != null) ...[
                      pw.Text(
                        branch.branchName,
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                      if (branch.branchAddress != null)
                        pw.Text(
                          branch.branchAddress!,
                          style: const pw.TextStyle(fontSize: 10),
                        ),
                      if (branch.contact != null)
                        pw.Text(
                          'Contact: ${branch.contact!}',
                          style: const pw.TextStyle(fontSize: 10),
                        ),
                    ],
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      'WAYBILL / DISPATCH NOTE',
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 18,
                        color: PdfColors.blue900,
                      ),
                    ),
                    pw.SizedBox(height: 5),
                    pw.Text(
                      'Date: ${_dateFormat.format(waybill.dispatchDate)}',
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                    pw.Text(
                      'Doc #: ${waybill.dispatchDocNumber}',
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue800,
                      ),
                    ),
                    pw.Text('Order #: ${waybill.orderNumber}'),
                    pw.Text(
                      'Generated By: ${waybill.createdBy}',
                      style: const pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.Text('Generated By: ${waybill.createdBy}'),
                  ],
                ),
              ],
            ),

            pw.SizedBox(height: 30),

            // Dispatch Info
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'DRIVER:',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                        ),
                      ),
                      pw.SizedBox(height: 5),
                      pw.Text(
                        waybill.senderName,
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                ),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'TO (DESTINATION):',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                        ),
                      ),
                      pw.SizedBox(height: 5),
                      pw.Text(
                        waybill.partyName,
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                        ),
                      ),
                      pw.Text(
                        waybill.destination,
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                    ],
                  ),
                ),
              ],
            ),

            pw.SizedBox(height: 30),

            // Packing Table
            pw.Table(
              border: pw.TableBorder.all(width: 0.5, color: PdfColors.grey400),
              columnWidths: {
                0: const pw.FlexColumnWidth(1),
                1: const pw.FlexColumnWidth(4.5),
                2: const pw.FlexColumnWidth(1.2),
                3: const pw.FlexColumnWidth(1.5),
                4: const pw.FlexColumnWidth(1.2),
                5: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _tableHeader('Sl No.', align: pw.TextAlign.center),
                    _tableHeader('Item Description'),
                    _tableHeader('Qty', align: pw.TextAlign.center),
                    _tableHeader('Rate', align: pw.TextAlign.right),
                    _tableHeader('Disc', align: pw.TextAlign.center),
                    _tableHeader('Total', align: pw.TextAlign.right),
                  ],
                ),
                ...List.generate(items.length, (index) {
                  final item = items[index];
                  return pw.TableRow(
                    children: [
                      _tableCell(
                        (index + 1).toString(),
                        align: pw.TextAlign.center,
                      ),
                      _tableCell(item.productName),
                      _tableCell(
                        item.quantity.toString(),
                        align: pw.TextAlign.center,
                      ),
                      _tableCell(
                        _currencyFormat
                            .format(item.unitprice)
                            .replaceAll('GH¢', ''),
                        align: pw.TextAlign.right,
                      ),
                      _tableCell(
                        '${item.discountPercentage}%',
                        align: pw.TextAlign.center,
                      ),
                      _tableCell(
                        _currencyFormat
                            .format(item.totalAmount)
                            .replaceAll('GH¢', ''),
                        align: pw.TextAlign.right,
                      ),
                    ],
                  );
                }),
              ],
            ),

            pw.SizedBox(height: 20),

            // Tax Summary Section
            pw.Row(
              children: [
                pw.Spacer(flex: 2),
                pw.Expanded(
                  flex: 1,
                  child: pw.Column(
                    children: [
                      _summaryRow(
                        'Item Subtotal',
                        _currencyFormat.format(
                          items.fold(
                            0.0,
                            (sum, item) => sum + item.totalAmount,
                          ),
                        ),
                      ),
                      ...waybill.mainContent.tax.map(
                        (t) => _summaryRow(
                          t.tax.name,
                          _currencyFormat.format(t.taxAmount),
                        ),
                      ),
                      pw.Divider(thickness: 1),
                      pw.Container(
                        padding: const pw.EdgeInsets.symmetric(vertical: 5),
                        child: pw.Row(
                          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                          children: [
                            pw.Text(
                              'GRAND TOTAL',
                              style: pw.TextStyle(
                                fontWeight: pw.FontWeight.bold,
                                color: PdfColors.blue900,
                              ),
                            ),
                            pw.Text(
                              _currencyFormat.format(
                                waybill.mainContent.totalAmount,
                              ),
                              style: pw.TextStyle(
                                fontWeight: pw.FontWeight.bold,
                                fontSize: 13,
                                color: PdfColors.blue900,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),

            if (waybill.deliveryNote.isNotEmpty) ...[
              pw.SizedBox(height: 20),
              pw.Text(
                'DELIVERY NOTES:',
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10,
                ),
              ),
              pw.SizedBox(height: 5),
              pw.Text(
                waybill.deliveryNote,
                style: const pw.TextStyle(fontSize: 9),
              ),
            ],

            pw.Spacer(),

            // Signature Section
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 40),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _signatureBox('Driver\'s Signature'),
                  _signatureBox('Security Check'),
                  _signatureBox('Receiver Name & Sign'),
                ],
              ),
            ),
          ];
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.center,
            padding: const pw.EdgeInsets.only(top: 20),
            child: pw.Text(
              'Kumasi Ashfoam - Official Dispatch Document',
              style: pw.TextStyle(
                fontStyle: pw.FontStyle.italic,
                fontSize: 9,
                color: PdfColors.grey700,
              ),
            ),
          );
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _signatureBox(String label) {
    return pw.Column(
      children: [
        pw.Container(
          width: 130,
          decoration: pw.BoxDecoration(
            border: const pw.Border(
              top: pw.BorderSide(width: 0.5, color: PdfColors.black),
            ),
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(label, style: const pw.TextStyle(fontSize: 8)),
      ],
    );
  }

  static pw.Widget _tableHeader(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
      ),
    );
  }

  static pw.Widget _tableCell(
    String text, {
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        textAlign: align,
        style: const pw.TextStyle(fontSize: 10),
      ),
    );
  }

  static pw.Widget _summaryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 9)),
          pw.Text(
            value,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          ),
        ],
      ),
    );
  }
}
