import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { CompanyHeaderA4 } from "./header";

export interface StockReportDocRow {
  name: string;
  openingQuantity: number;
  quantitySold: number;
  totalSales: number;
  quantityAdded: number;
  quantity: number;
}

export interface StockReportDocData {
  id: string;
  branchName: string;
  periodLabel: string;
  scopeLabel: string;
  createdBy: string;
  rows: StockReportDocRow[];
}

const MONTHS_FULL = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const pad = (n: number) => String(n).padStart(2, "0");

/** 'dd MMM yyyy HH:mm' for Printed On. */
function printedOn(d: Date): string {
  const M = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${pad(d.getDate())} ${M[d.getMonth()]} ${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/** 'MMMM yyyy' for filename + preview title. */
export function reportMonthLabel(createdAt: string): string {
  const d = new Date(createdAt);
  return `${MONTHS_FULL[d.getMonth()]} ${d.getFullYear()}`;
}

const money = (n: number) =>
  new Intl.NumberFormat("en-GH", {
    style: "currency",
    currency: "GHS",
  })
    .format(n ?? 0)
    .replace("GH₵", "")
    .replace("GH¢", "")
    .trim();

const s = StyleSheet.create({
  page: { padding: 32, fontFamily: "Helvetica" },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  branchCol: { alignItems: "flex-end" },
  branchName: { fontWeight: "bold" },
  scope: { fontSize: 9 },
  metaRow: { flexDirection: "row", justifyContent: "space-between" },
  metaCol: {},
  meta: { fontSize: 10 },
  reportId: { fontSize: 8, color: "#808080" },
  sectionTitle: { fontSize: 14, fontWeight: "bold" },
  sectionSub: { fontSize: 10, color: "#616161" },
  table: { borderWidth: 0.5, borderColor: "#BDBDBD" },
  headRow: {
    flexDirection: "row",
    backgroundColor: "#EEEEEE",
  },
  row: { flexDirection: "row" },
  c0: { flex: 3, padding: 5 },
  c1: { flex: 1, padding: 5 },
  c2: { flex: 1, padding: 5 },
  c3: { flex: 2, padding: 5 },
  c4: { flex: 1, padding: 5 },
  c5: { flex: 1, padding: 5 },
  th: { fontSize: 10, fontWeight: "bold" },
  td: { fontSize: 9 },
  center: { textAlign: "center" },
  right: { textAlign: "right" },
  footnote: { fontSize: 8, color: "#616161" },
  signLine: { fontSize: 10 },
  footer: { fontSize: 9, color: "#808080", textAlign: "right" },
});

/**
 * Stock movement report — exact port of StockReportPrintService:
 * company header + branch/period block, meta row, grey-header product
 * table, footnote, signature line, page footer.
 */
export function StockReportDoc({ doc }: { doc: StockReportDocData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.topRow}>
          <CompanyHeaderA4 />
          <View style={s.branchCol}>
            <Text style={s.branchName}>{doc.branchName}</Text>
            <Text>{doc.periodLabel}</Text>
            <Text style={s.scope}>{doc.scopeLabel}</Text>
          </View>
        </View>

        <View style={{ height: 20 }} />
        <View style={s.metaRow}>
          <View style={s.metaCol}>
            <Text style={s.meta}>Generated By: {doc.createdBy}</Text>
            <Text style={s.meta}>Printed On: {printedOn(new Date())}</Text>
          </View>
          <View style={s.metaCol}>
            <Text style={s.reportId}>
              Report ID: {doc.id.substring(0, 8)}...
            </Text>
          </View>
        </View>

        <View style={{ paddingVertical: 20 }}>
          <View
            style={{ borderBottomWidth: 0.5, borderColor: "#000" }}
          />
        </View>

        <Text style={s.sectionTitle}>STOCK MOVEMENT</Text>
        <View style={{ height: 4 }} />
        <Text style={s.sectionSub}>
          {doc.periodLabel} · {doc.scopeLabel}
        </Text>
        <View style={{ height: 10 }} />

        <View style={s.table}>
          <View style={s.headRow}>
            <View style={s.c0}>
              <Text style={s.th}>Product</Text>
            </View>
            <View style={s.c1}>
              <Text style={[s.th, s.center]}>Opening</Text>
            </View>
            <View style={s.c2}>
              <Text style={[s.th, s.center]}>Sold</Text>
            </View>
            <View style={s.c3}>
              <Text style={[s.th, s.right]}>Sales Value</Text>
            </View>
            <View style={s.c4}>
              <Text style={[s.th, s.center]}>Added</Text>
            </View>
            <View style={s.c5}>
              <Text style={[s.th, s.center]}>Closing</Text>
            </View>
          </View>
          {doc.rows.map((r, i) => (
            <View key={i} style={s.row}>
              <View style={s.c0}>
                <Text style={s.td}>{r.name}</Text>
              </View>
              <View style={s.c1}>
                <Text style={[s.td, s.center]}>{r.openingQuantity}</Text>
              </View>
              <View style={s.c2}>
                <Text style={[s.td, s.center]}>{r.quantitySold}</Text>
              </View>
              <View style={s.c3}>
                <Text style={[s.td, s.right]}>{money(r.totalSales)}</Text>
              </View>
              <View style={s.c4}>
                <Text style={[s.td, s.center]}>{r.quantityAdded}</Text>
              </View>
              <View style={s.c5}>
                <Text style={[s.td, s.center]}>{r.quantity}</Text>
              </View>
            </View>
          ))}
        </View>
        <View style={{ height: 6 }} />
        <Text style={s.footnote}>
          Opening quantities and quantities added are derived from recorded
          stock movements.
        </Text>

        <View style={{ paddingVertical: 40 }}>
          <View
            style={{ borderBottomWidth: 1, borderColor: "#E0E0E0" }}
          />
          <View style={{ height: 5 }} />
          <Text style={s.signLine}>
            Authorized Signature: ___________________________
          </Text>
        </View>
        <Text
          style={s.footer}
          fixed
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          }
        />
      </Page>
    </Document>
  );
}
